---
general:
  numClass: 2
  displayNet: true
  x_data_path: "data/Massive_ariel/low_X/lowX_spectra.npy"
  y_data_path: "data/Massive_ariel/low_X/lowX_param_file.csv"
  checkpoint_dir: 'output/cnn/trans_reduced_32_dense64_org_opt_nosensi/'
  seed: 42

training:
  train: true
  useCNN: true
  useMLP: false
  useLSTM: false
  decay: -4
  dropRate: 0.3
  lossFn: "mse"
  extraInput: false
  shuffleTimes: 10
  cv: 5


CNN:
  layers: [ 32,32,32]
  kernels: [3,3,3]
  activation: "relu"
  stride: [1,1,1]
  batchNorm: [1,1,1]
  maxPool: [1,1,0]
  denseUnit: 64
  denseActi: "leakyRELU"

MLP:
  layers: [ 320,240,160,80]
  activation: "relu"

LSTM:
  layers: [100,100]
  denseUnit: 16
  lstmActi: 'tanh'
  maxPool: [1,1]



